server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/predictdividentdb
    username: postgres
    password: postgres


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  url: https://financialmodelingprep.com/api
  token: apikey=EklueuaDiiIs1JpIOeTMFgqQAfRra2an


jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte
