server:
  port: 8083
spring:
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/predictdividentdb
    username: postgres
    password: postgres
# ===============================
# = Email SMTP configurations
# ===============================
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ilya.dashko228@gmail.com
    password: ihbcewkbijsuutbe
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  url: https://financialmodelingprep.com/api
  token: apikey=EklueuaDiiIs1JpIOeTMFgqQAfRra2an
  token_2: apikey=4f0212439d2fbcca3ab6d60c3f1d15a7
  token_3: apikey=ju4PSxzDgKLkx9Mw9JHAjQEDsxFfCBrC
  token_4: apikey=c5d10e1f951076188279d786fb91dea1
currency-api:
  url: https://v6.exchangerate-api.com/v6/
  token: adefc15712cfbc6e54ec0f52
# ===============================
# = JWT configurations
# ===============================
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte
