import {Component, EventEmitter, Output} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.css'],
})
export class FilterComponent {
  @Output() formDataEvent = new EventEmitter<any>();

  filterForm: FormGroup;
  sectors = new FormControl([]);
  countries = new FormControl([]);
  industries = new FormControl([]);

  constructor(private fb: FormBuilder) {
    this.filterForm = this.fb.group({
      sectors: this.sectors,
      industries: this.industries,
      countries: this.countries,
      priceMoreThan: [null, Validators.min(0)],
      priceLowerThan: [null, Validators.min(0)]
    });
  }

  filterResults() {
    this.formDataEvent.emit(this.filterForm.value);
  }
  sectorList: string[] = [
    'Consumer Cyclical',
    'Energy',
    'Technology',
    'Industrials',
    'Financial Services',
    'Basic Materials',
    'Communication Services',
    'Consumer Defensive',
    'Healthcare',
    'Real Estate',
    'Utilities',
    'Industrial Goods',
    'Financial',
    'Services',
    'Conglomerates',
  ];
  countryList: string[] = [
    'FK',
    'RU',
    'INE',
    'DK',
    'SI',
    'SN',
    'CZ',
    'KR',
    'MYL',
    'JP',
    'BS',
    'AU',
    'CL',
    'QA',
    'NET',
    'MZ',
    'EE',
    'GE',
    'BM',
    'AT',
    'CI',
    'LI',
    'VN',
    'KW',
    'AR',
    'EGS',
    'BR',
    'NA',
    'PL',
    'ARDEUT',
    'MT',
    'MC',
    'GI',
    'EG',
    'SA',
    'DE',
    'United States',
    'INF',
    'SK',
    'LT',
    'SR',
    'MU',
    'CY',
    'BB',
    'HU',
    'UK',
    'FI',
    'KG',
    'IE',
    'JE',
    'RE',
    'BD',
    'UA',
    'DO',
    'ES',
    'NO',
    'TH',
    'TR',
    'MA',
    'CO',
    'BE',
    'AN',
    'GF',
    'AZ',
    'GL',
    'MM',
    'PE',
    'CK',
    'US',
    'SG',
    'NZ',
    'KZ',
    'AE',
    'UY',
    'NL',
    'IN',
    'CN',
    'ME',
    'ZM',
    'TC',
    'MY',
    'HK',
    'MQ',
    'BW',
    'VG',
    'PLINPRO',
    'AI',
    'SE',
    'CH',
    'LU',
    'TW',
    'CA',
    'PR',
    'FR',
    'KY',
    'LV',
    'PG',
    'MX',
    'RO',
    'GG',
    'CW',
    'TZ',
    'MO',
    'PH',
    'GA',
    'IM',
    'ID',
    'MN',
    'PA',
    'XS',
    'ZA',
    'PT',
    'NG',
    'IL',
    'JO',
    'BG',
    'IT',
    'GB',
    'IS',
    'CR',
    'KH',
    'MK',
    'GR',
    'KYG',
  ];
  industryList: string[] = [
    'Autos',
    'Banks Diversified',
    'Software',
    'Banks Regional',
    'Beverages Alcoholic',
    'Beverages Brewers',
    'Beverages Non-Alcoholic',
  ];
}
